[package]
name = "rs-taskmanager"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.26"
tokio = { version = "1.25.0", features = [
    "signal",
    "macros",
    "time",
    "sync",
    "rt",
] }
waitgroup = "0.1.2"
